# Generated by Django 5.2 on 2025-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='address_city',
        ),
        migrations.AddField(
            model_name='company',
            name='address_street',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
