# Generated by Django 5.2 on 2025-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_address_company_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Duties',
        ),
    ]
